Repository isislovecruft/python-gnupg, pull requests merged in 2018-07, with the labels that each got.

#238 Fix gpg>=1.4.18 bug where --edit-key continually asks for a passphrase.
  pretty_bad_protocol/gnupg.py
Labels: compatibility, upstream GnuPG bug

#173 Bail if version string is bogus
  gnupg/_meta.py
  gnupg/test/test_gnupg.py
  setup.py
Labels: bug, compatibility

#178 Silence homedir warnings from gpg
  gnupg/_meta.py
Labels: enhancement

#183 Handle PROGRESS status message
  gnupg/_parsers.py
Labels: bug

#185 Vinay's project has moved, saves us the extra hop.
  README
Labels: documentation

#190 README - add syntax highlighting
  README
Labels: documentation

#212 Fix for KEY_CONSIDERED issue
  gnupg/_parsers.py
Labels: bug, compatibility
